### ISSUE TITLE
2.5i Board compatibility

### ISSUE THREAD

**Issue by shanelord01** [ratgdo/esphome-ratgdo#109]
Hi,

I just received two 2.5i boards. They use the ESP-12F which has integrated WiFi, ESP8266 and PCB antenna.

I have successfully loaded the "ESPHome config for v2.5 board with ESP8266 D1 Mini lite" on these. Just wanted to ensure I'm OK to do so (seems to be running OK).

![ratgdo-2 5i](https://github.com/ratgdo/esphome-ratgdo/assets/49434655/c4f46b60-6dad-4235-a261-78c8d736ef1a)

Thanks,
Shane.

**Comment by PaulWieland** [comment]
Yes, its fine.

**Comment by BEFH** [comment]
Does 2.5 support setting exact garage door position? It doesn't seem like this revision allows soldering to the mainboard.

**Comment by PaulWieland** [comment]
No soldering is needed. Version 1.0 of ratgdo required soldering, but there are very few of those in existence and none of them are supported by ESP Home at all.
