### ISSUE TITLE
Use on a ESP32 Dev Board

### ISSUE THREAD

**Issue by DJAMIRSAM** [ratgdo/esphome-ratgdo#121]
I fell like im being dumb because nobody else asked this but if I wanted to use this with an ESP32 Dev Board what pins would i need to connect? and which package do i need to install?

**Comment by DJAMIRSAM** [comment]
to add this is a bare board not one purchased from the site

**Comment by SomeGuy581** [comment]
You will need to add a few resistors and MOSFETs. See https://github.com/Kaldek/rat-ratgdo

And others have asked but Paul isn't willing to release his schematics and deletes the question. I expect this will be deleted when he sees it and I may be banned from this repo.

**Comment by mariusmuja** [comment]
> I fell like im being dumb because nobody else asked this but if I wanted to use this with an ESP32 Dev Board what pins would i need to connect? and which package do i need to install?

Do you mean to use an ratgdo shield with an esp32 dev board? Look at the yaml file for an esp32 board (v2board_esp32_d1_mini.yaml for example) and the same version ratgdo board as you have (2.0 or 2.5) and translate the pin names as in the image [here](https://templates.blakadder.com/wemos_D1_Mini_ESP32.html), for example `D2` -> `GPIO21`.

**Comment by DJAMIRSAM** [comment]
> Do you mean to use an ratgdo shield with an esp32 dev board? Look at the yaml file for an esp32 board (v2board_esp32_d1_mini.yaml for example) and the same version ratgdo board as you have (2.0 or 2.5) and translate the pin names as in the image [here](https://templates.blakadder.com/wemos_D1_Mini_ESP32.html), for example `D2` -> `GPIO21`. 
> 
> 
> 
> 

How would I translate the pin names? And I have a esp32 dev board which still uses the D-pins but the ones that are being used in the code don't line up with my board, which ones do I need to change (and what to) to get it to work with a esp32 dev (not mini) board? And do I have to change other things in the code as-well?

**Comment by rlowens** [comment]
You didn't answer the questions.

Do you mean to use a ratgdo shield with an esp32 dev board?

Also, what version of ratgdo board and exactly what esp32 dev board (link or paste a picture please).

For example, if you were using a ratgdo v2.5 with a D1 mini-style ESP32 board like this:
![image](https://github.com/ratgdo/esphome-ratgdo/assets/35885181/56d5e168-4df1-4b0c-8cc7-e25cb7533c22)
![image](https://github.com/ratgdo/esphome-ratgdo/assets/35885181/7a0d71b4-f159-4c83-9eb0-57e574c03b27)

You would just use this esphome configuration: https://github.com/ratgdo/esphome-ratgdo/blob/main/static/v25board_esp32_d1_mini.yaml

**Comment by DJAMIRSAM** [comment]
> You didn't answer the questions.
> 
> Do you mean to use a ratgdo shield with an esp32 dev board?
> 
Ah my bad I didn’t understand the question, 


This is the board I have 
https://lastminuteengineers.com/esp32-pinout-reference/

**Comment by SomeGuy581** [comment]
So you do not have a ratgdo, correct? To connect that dev board without a ratgdo you will need several resisters and MOSTFETs. See my link above.

**Comment by donavanbecker** [comment]
Would this one work?

https://a.co/d/eZOa2N6

**Comment by shivaagarwal1** [comment]
> > You didn't answer the questions.
> > Do you mean to use a ratgdo shield with an esp32 dev board?
> 
> Ah my bad I didn’t understand the question,
> 
> This is the board I have https://lastminuteengineers.com/esp32-pinout-reference/

Did you figure it out? I have the same board and wondering if I can create RATGDO at home.

**Comment by DJAMIRSAM** [comment]
Just ended up buying it , helps our the community and realistically it’s worth it

**Comment by shivaagarwal1** [comment]
> Just ended up buying it , helps our the community and realistically it’s worth it

Thank you. Shipping to Canada is expensive, but I guess it is what it is.
