### ISSUE TITLE
ETA on Esphome version for Security + 1.0

### ISSUE THREAD

**Issue by restauffer** [ratgdo/esphome-ratgdo#126]
Is there a rough ETA on the Esphome version for Security + 1.0? Are we talking days, weeks, months, possibly never?

I am not complaining just trying to decide if I should go ahead with the MQTT version and then have to convert later, or just wait a bit more.

Thanks

**Comment by bdraco** [comment]
There is no ETA yet. I'd go ahead with the MQTT version for now

**Comment by restauffer** [comment]
Thanks for the speedy reply.
