### ISSUE TITLE
Compatible with 'Linear' GDO

### ISSUE THREAD

**Issue by leowang16** [ratgdo/esphome-ratgdo#145]
Hello, I have a 'Linear' GDO, with a gray dot learn button and 3 terminals (1 common terminal) for the wall button and the obstruction detector (the panel like this [figure](https://learngaragedoors.com/wp-content/uploads/2022/10/linear-diagnostic-chart-back-of-ldco800-linear-opener-Large-1024x768.jpeg)). I have tried several wiring methods, but the issues is always 'ratgdov2.5i sync failed. Failed to communicate with garage opener on startup; Check the ratgdov2.5i Rolling code counter number entity history and set the entity to one number larger than the largest value in history' in HA. I assume I might have the wrong wiring, or it is the compatibility issue. If someone could provide some valuable help, that would be great. Thanks!
Linear GDO
![image](https://github.com/ratgdo/esphome-ratgdo/assets/26159842/dc8bd4a7-13d8-4736-9878-b33dadf48050)
v2.5 dry contact diagram:
![image](https://github.com/ratgdo/esphome-ratgdo/assets/26159842/54f39001-637e-47a3-abb2-a6734a5ec7f8)

**Comment by rlowens** [comment]
> v2.5 dry contact diagram:

esphome-ratgdo firmware only supports Security+ 2.0 GDO's currently. For Security+ 1.0 or Dry Contact control, you have to use the mqtt-ratgdo firmware currently. See the feature support matrix here https://paulwieland.github.io/ratgdo/01_features.html
