### ISSUE TITLE
Wired correctly, powers on and connects to wifi and HA but doesnt control door/lights/etc

### ISSUE THREAD

**Issue by changes13** [ratgdo/esphome-ratgdo#166]
[I have this panel ](https://www.amazon.com/Chamberlain-41A6317-Original-Equipment-Manufacturer/dp/B071CRNQC4/ref=cm_cr_arp_d_product_top?ie=UTF8)

log: [without panel then with panel.txt](https://github.com/ratgdo/esphome-ratgdo/files/13826502/without.panel.then.with.panel.txt)

Motor: ![PXL_20240104_050632315](https://github.com/ratgdo/esphome-ratgdo/assets/113197804/8936d94b-bc8f-4dad-83d9-a92630a64c9c)

Context:
The first boot, the panel is not connected.
I rebooted with the panel connected later on in the log session.
In both cases I manually tried to open, close, light on/off, and sync.

What happens:
In both cases, ratgdo does not control the motor or the light.  

Additional info:
Random time where the door opened during boot or manual sync.
The panel is fully functional when wired even with ratdgo connected.
ratgdo always reports door open even when it is closed.
Quadruple checked wiring.

Any help appreciated!

**Comment by wastingaeons** [comment]
looks like a secplus1 device, flash the mqtt firmware as this firmware doesn't support secplus1 yet.

**Comment by changes13** [comment]
flashed mqtt.  works mostly (sometimes a command doesnt work)
