### ISSUE TITLE
Does not work with Chamberlain RollerLift CR655MYQ 

### ISSUE THREAD

**Issue by anuragpathak21** [ratgdo/esphome-ratgdo#176]
I am using Australian Chamberlain RollerLift CR655MYQ model.

Tried ESPHome ratgdo with ratgdo 2.5 version following Version 2.5i Security + 1/2 Wiring Diagram
but it doesn't work.

Below is the iwring diagram of the RollerLift

![image](https://github.com/ratgdo/esphome-ratgdo/assets/50142570/a1d09d90-262a-469c-bebe-56ea013a6987)

**Comment by stevearmitage** [comment]
my RATGDO arrived yesterday (16-Jan)
I have the same issues connecting to my roller door (same model as above)

I have installed the latest ESPHome firmware
```
esphome
by ratgdo
Firmware: 2023.12.7 (Jan 17 2024, 11:18:45)
Hardware: 2.5i
```

I get the following notification in Home Assistant when the RATGDO reboots
```
GDO Workshop sync failed
Failed to communicate with garage opener on startup; Check the GDO Workshop Rolling code counter number entity history and set the entity to one number larger than the largest value in history.
```

The startup logs
```
11:20:43 | [D] | [number:012] | 'Rolling code counter': Sending state 40.000000
-- | -- | -- | --
11:20:44 | [D] | [api.connection:1121] | Home Assistant 2024.1.3 (192.168.67.4): Connected successfully
11:20:44 | [D] | [time:044] | Synchronized time: 2024-01-17 11:20:44
11:20:45 | [D] | [esp8266.preferences:238] | Saving preferences to flash...
11:20:49 | [D] | [number:012] | 'Rolling code counter': Sending state 41.000000
11:20:50 | [D] | [esp8266.preferences:238] | Saving preferences to flash...
11:20:57 | [D] | [number:012] | 'Rolling code counter': Sending state 42.000000
11:21:00 | [D] | [esp8266.preferences:238] | Saving preferences to flash...
11:21:10 | [D] | [ratgdo:545] | Triggering sync failed actions.
11:21:10 | [D] | [number:012] | 'Rolling code counter': Sending state 43.000000
11:21:15 | [D] | [esp8266.preferences:238] | Saving preferences to flash...
```

Here are how the device properties show in Home Assistant
<img width="332" alt="Screenshot 2024-01-17 at 11 13 39" src="https://github.com/ratgdo/esphome-ratgdo/assets/29444933/f5a29625-0473-4164-be80-49b60025b8ef">
<img width="332" alt="Screenshot 2024-01-17 at 11 13 30" src="https://github.com/ratgdo/esphome-ratgdo/assets/29444933/2332b8c1-aee9-4fd8-bfc7-e2bd4dce3538">
<img width="328" alt="Screenshot 2024-01-17 at 11 13 47" src="https://github.com/ratgdo/esphome-ratgdo/assets/29444933/b40e0756-1201-43a5-9c31-b9af3af6f0b5">

Would appreciate any ideas.

**Comment by PaulWieland** [comment]
This model door opener doesn't have a serial communication port. You have to use dry contact control with it.

**Comment by JustDFB** [comment]
As in use the dry contract protocol that doesn't exist for EPSHome yet (coming soon)?
If so, any ETA please as it appears there are a number of us in the same situation....
It does support 2.0 - unsure if that is relevant.
Thanks

**Comment by steveshacks** [comment]
Bump. I also have this door and have been unable to get it working using Security protocol (red & white wires).

**Comment by wotacs** [comment]
> Bump. I also have this door and have been unable to get it working using Security protocol (red & white wires).

Paul commented above that the CR655MYQ Opener does not support Security protocol. 

We both need to use a dry contact to operate our doors. Bit of a shame, actually. I've just received my 2 units to control my doors. I guess my next step is going to be hacking the radio signal side of things, either the Remote to Motor (433.92Mhz) or preferably the Hub to Motor protocol, which may carry more information as it looks to be a bi-directional link.

**Comment by PaulWieland** [comment]
Dry contact support has been implemented in the ESP Home firmware.

**Comment by anuragpathak21** [comment]
> Dry contact support has been implemented in the ESP Home firmware.

What does that mean for my setup. Will it work using ratgdo 2.5 for my Australian Chamberlain RollerLift CR655MYQ model following the wiring diagram Version 2.5i Security + 1/2 Wiring Diagram 
or do I have to make any changes or add reed switch ? 


![image](https://github.com/user-attachments/assets/9ff832d7-e3ce-43d7-8faf-fdac912a7088)

**Comment by chriscollingwood613** [comment]
@mborawi , @anuragpathak21 Chamberlain didn't make the CR655MYQ units use the fancy secure serial protocol for local control, which means the only option for you (and me) is going to be to use the RATGDO to deliver a contact closure to the motor control port or learn how to hack the radio protocol that goes between the opener and the control hub. I started assembling the tools to try and hack the hub-motor protocols but ran out of mental energy before I could complete that task. Have a read of the documentation around the RATGDO, you need to put it into contact mode and also add door-closed indicator reed switches.

**Comment by hwmaier** [comment]
Are there any news how to integrate the CR655MYQ or the cheaper HERDO1 (same hardware as CR655MYQ  from Bunnings) with the smarter Security+ protocol? I am keen to monitor the state of the door like opened/closed/opening rather simple toggle on/off control.
