### ISSUE TITLE
Apparent issue with esphome web installer.

### ISSUE THREAD

**Issue by PedanticAvenger** [ratgdo/esphome-ratgdo#180]
Just received my 2.5i board and went to flash it with the Esphome image.
Select board and type (Sec+1.0) and click connect, select COM port and then error "Failed to download manifest" pops up.
Reproduceable on Edge/Chrome/Firefox and my previous unit (before I realized I didn't have a Sec+2.0 opener) flashed fine.

Something change on the page recently?

**Comment by PedanticAvenger** [comment]
To update, selecting 2.5i w/ Security+2.0 as an option proceeds properly to flashing without an error.

**Comment by bercribe** [comment]
I just tried the same thing, having the exact same issue

**Comment by bdraco** [comment]
Try clearing your browser cache. The firmware files for the 2.5i and 2.5 board should be up there now

**Comment by PedanticAvenger** [comment]
Confirmed.
Thanks!
