### ISSUE TITLE
[Request] Description of fields/functions.

### ISSUE THREAD

**Issue by LF-Tech** [ratgdo/esphome-ratgdo#198]
I am currently using/testing the device directly by browsing to the IP via a web browser. I might be missing this somewhere in the repository but is there a description or explanation for each line. Some are self explanatory, such as Motor ON means the motor is running, but others I am not sure about. What is the Button state? What does sync do? Is learn the same thing as pressing the learn button on the motor itself? Etc.

Thanks in advance and apologies if this is already mapped out somewhere or this is not the proper way to submit this request.

**Comment by PaulWieland** [comment]
https://ratgdo.github.io/esphome-ratgdo/webui_documentation.html
