### ISSUE TITLE
ESPHome install page pointing to incorrect firmware file?

### ISSUE THREAD

**Issue by PaulWieland** [ratgdo/esphome-ratgdo#209]
@mariusmuja oddly I flashed the ESPHome firmware with Security 1.0 to my RATGDO 2.5i board; however the log entries reference sec2plus ([ratgdo_secplus2:xxx]). Is the ESPHome install page pointing to incorrect firmware file?

_Originally posted by @miles267 in https://github.com/ratgdo/esphome-ratgdo/issues/128#issuecomment-1912405253_

**Comment by miles267** [comment]
Following this thread for production fix. Thanks.
