### ISSUE TITLE
Ratgdo ESPHome 8500W failed after update

### ISSUE THREAD

**Issue by bill7531** [ratgdo/esphome-ratgdo#242]
I updated one of my ratgdo to firmware 2023.12.9 March 9 15:45:30. It had stopped working since. The log prints discarded incomplete packet repeatedly. I have the 2.5i version.

![image](https://github.com/ratgdo/esphome-ratgdo/assets/29690006/111c6567-2ef3-47ab-9649-4f5d252420d7)

My 2 other 8500W on firmware 2023.12.8 (Jan 22 2024, 04:19:20) are still working. How do I solve this or is there anyway to downgrade?

edit: strangely choosing the sec plus 2.0 fixed the issue. (Yes I do have 8500w and chose 1.0 last time.

**Comment by PaulWieland** [comment]
You installed Security + 1.0. The 8500W is Security + 2.0

<img width="411" alt="image" src="https://github.com/ratgdo/esphome-ratgdo/assets/4663918/82dd73c8-6e43-4574-9fc5-b25ed85975ac">
