### ISSUE TITLE
Sec+ 1.0: light wall button not working

### ISSUE THREAD

**Issue by neheb** [ratgdo/esphome-ratgdo#251]
I wired up ratgdo to my Liftmaster and found out that I can control everything in Home Assistant, including the light. However the light button on the wall no longer works. I assume this is a firmware issue as ratgdo can control the light just fine.

**Comment by rlowens** [comment]
From the FAQ https://paulwieland.github.io/ratgdo/09_faq.html

> **My Security + 1.0 wall panel’s light and lock buttons don’t work after connecting ratgdo**
> You have an analog control wall panel. ratgdo in Security + 1.0 control mode requires a digital communication with the garage door opener in order to both control the door and to get the door’s status. When the door opener is in digital communication mode, the analog light and lock controls are ignored.
> 
> If this is a deal breaker for you, you have two choices:
> 
> Use ratgdo’s dry contact control and reed switches to get the door status
> Buy a digital wall control which is myQ compatible such as the 889LM / 041A7928-3MC.

**Comment by neheb** [comment]
hrm that's unfortunate. Guess I'll just install a smart switch.

**Comment by restauffer** [comment]
Don’t dismiss Paul’s suggestion of the. 889LM wall panel too quickly . It replaces your current panel and allows both Ratgdo and regular control of the door.  I am happy with mine.

**Comment by neheb** [comment]
rather pricey. The big button works just fine. Since I have switches lying around, easier to just use that.

**Comment by neheb** [comment]
@restauffer I see there's a cheaper 888LM. I assume that wouldn't work?

**Comment by doctorkb** [comment]
It appears the 889lm replaced the 888lm, the latter of which has been discontinued.

I suspect they both use the needed signal type.

**Comment by doctorkb** [comment]
Note, however: https://www.cpsc.gov/Recalls/2023/Chamberlain-Group-Recalls-LiftMaster-myQ-Garage-Door-Control-Panels-Due-to-Entrapment-Hazard-Recall-Alert

That may be why it was replaced...

**Comment by restauffer** [comment]
> @restauffer I see there's a cheaper 888LM. I assume that wouldn't work?

doctorkb has the correct answer.  The 889lm replaced the 888lm due to problems with capacitors in the 888lm.

**Comment by neheb** [comment]
So on recommendation of people here, I bought the 889lm. Now my garage door randomly opens and closes. This thing is pure garbage.

**Comment by neheb** [comment]
Oh this is a ratgdo bug. Lovely.
