### ISSUE TITLE
Critical - door randomly opened randomly

### ISSUE THREAD

**Issue by 4vanger** [ratgdo/esphome-ratgdo#254]
I came outside yesterday and to my surprise garage door was fully opened but nobody at home did that. I freshly reflashed ratgdo just few days ago with esphome because mqtt was becoming unresponsive. Because I freshly updated it I didn't had a chance to update my automations so I don't think this is one of them opening the door.
esphome by ratgdo
Firmware: 2024.3.2 (Apr 8 2024, 04:18:40)
Hardware: 2.5i
MAC: AC:0B:FB:E4:38:A1
Home Assistant 
![h8IpMbM 1](https://github.com/ratgdo/esphome-ratgdo/assets/596990/9d696c50-c1a8-4ace-8970-0b57e45ec75b)

**Comment by PaulWieland** [comment]
Please update to latest release

**Comment by mikecarr** [comment]
I have been having this issue lately, I downloaded latest from GitHub and it is part of esphome.
