### ISSUE TITLE
Obstruction detected in CarPlay, but not in home app

### ISSUE THREAD

**Issue by ItsHaysus** [ratgdo/esphome-ratgdo#269]
Not sure if this is a HK issue or a HA issue or a ESPHOME issue

the garage door works flawlessly in HK, and HA but when trying to use it on CarPlay it gives me “obstruction detected” on the screen.

im wondering if I forgot to expose a sensor? Has anyone had this issue?

I hate attached photos of the issue
![IMG_6254](https://github.com/ratgdo/esphome-ratgdo/assets/16965883/1873b507-7fdf-4f4a-b1f6-386b1ad7b538)
![IMG_6253](https://github.com/ratgdo/esphome-ratgdo/assets/16965883/1627b438-a841-4a5b-99e7-39c028d1761e)

**Comment by PaulWieland** [comment]
Check the ratgdo WebUI and make sure the state of the sensor is correct. Assuming it is, this is not a ratgdo issue.
