### ISSUE TITLE
Up vs Down Arrow In Home Assistant

### ISSUE THREAD

**Issue by rtvanhook** [ratgdo/esphome-ratgdo#274]
Brilliant piece of work.  Works flawlessly.  I hate to bring up the 0.01% when 99.99% is amazing, but...

The up and down arrow icons seem to be exchanged in the HA UI.  I'm integrating via ESPHome firmware.

See attached screen shot.

![IMG_5081](https://github.com/ratgdo/esphome-ratgdo/assets/21115451/565bfe04-be32-4312-bd7b-7f73dfc2a916)

In the HA device screen for "Door", it shows an up arrow, a square, and a down arrow.  At least that's how the icons strike me.

Best I can tell, either the up or down arrow is solid and the other grayed to show the door open or closed.

To me, a solid up arrow means open (i.e., door up), and a solid down arrow means closed (i.e., door down).

That doesn't seem to be the case.  That screen shot is with the door closed, and the up arrow is solid.

Maybe it's just my brain.  Again...it works fine, and thank you so much for sharing your brilliance with the world.

**Comment by PaulWieland** [comment]
The icons are buttons for controlling the door. When the door is closed, you can't close it and vice versa.

**Comment by rtvanhook** [comment]
So the up arrow is telling me?  Intuitively, it tells me that the door is up.  I'm certainly willing to recalibrate.

**Comment by rtvanhook** [comment]
Problem with intuition is that everyone's works differently.  Sorry.
