### ISSUE TITLE
Up vs Down Arrow

### ISSUE THREAD

**Issue by rtvanhook** [ratgdo/esphome-ratgdo#275]
Hate to bug you again...

![IMG_5081 (Markup)](https://github.com/ratgdo/esphome-ratgdo/assets/21115451/598af208-d552-44f6-b02c-884eedac3b6b)

The up arrow should be telling me what?

Intuitively, it's telling me that the door is up.  But the problem with intuition is that everyone's is different.

**Comment by PaulWieland** [comment]
This isn’t a status icon, It’s a control icon. If you tap it the door will open.
