### ISSUE TITLE
Component esphome.ota is marked FAILED

### ISSUE THREAD

**Issue by socal0001** [ratgdo/esphome-ratgdo#295]
I believe I am seeing this issue:  https://github.com/esphome/issues/issues/5952

My config has
ota:
  - platform: esphome
    password: !secret ota_password

but that conflicts with your config in base.yml
ota:
  - platform: esphome

Following are the logs.  This issue is possibly some of the other "Issues" here.

11:49:47	[C]	[esphome.ota:074]	
  Address: garage_door_wifi.iot.redacted.com:8266
11:49:47	[C]	[esphome.ota:075]	
  Version: 2
11:49:47	[C]	[esphome.ota:073]	
Over-The-Air updates:
11:49:47	[C]	[esphome.ota:074]	
  Address: garage_door_wifi.iot.redacted.com:8266
11:49:47	[C]	[esphome.ota:075]	
  Version: 2
11:49:47	[C]	[esphome.ota:078]	
  Password configured
11:49:47	[E]	[component:082]	
  Component esphome.ota is marked FAILED
11:49:47	[C]	[safe_mode:018]	
Safe Mode:
11:49:47	[C]	[safe_mode:019]	
  Boot considered successful after 60 seconds

**Comment by notjj** [comment]
@johnthomas00 try this instead:

```
ota:
  - id: !extend ratgdo_ota
    password: !secret ota_password
```

#296 just got merged which should let this work for you. The pull request covers the details as to what happened.
