### ISSUE TITLE
Dry contact toggle does not toggle door

### ISSUE THREAD

**Issue by cbuckley** [ratgdo/esphome-ratgdo#318]
Using the new open/close dry contacts toggle feature merged in https://github.com/ratgdo/esphome-ratgdo/pull/307 I can see that the two contacts are marked as `ON` in the UI and the toggle debug message is displayed but the door never moves and the position stays at 0%

This works sometimes, usually after a reboot but not after every reboot. I have tried also hitting up/down and toggle in the UI and this still works even when the dry contact toggle is broken.

<img width="1483" alt="Screenshot 2024-08-04 at 6 41 00 PM" src="https://github.com/user-attachments/assets/89e80aa5-e244-4820-a692-e98a406b09c9">

**Comment by evil-chimera** [comment]
I have the same issue with my 2 ratgdo's, toggle command shows in logs but the door will not move. 


![image](https://github.com/user-attachments/assets/e03632af-d4ad-444f-b787-6183de54e566)
![image](https://github.com/user-attachments/assets/41aa332f-149a-4eaa-95eb-7ae34b583673)

**Comment by PaulWieland** [comment]
You can see in both logs that it is triggering the toggle command:
<img width="465" alt="image" src="https://github.com/user-attachments/assets/7b96cdab-6b0a-41b1-a9aa-d0d99e7d8a86">

Followed by the rolling code counter being incremented which indicates that its transmitting the command to the GDO. 

Give that, I'm not sure what the issue could be. Does the door respond to the discrete open or close commands? Does it respond to the toggle button in the web ui?

**Comment by evil-chimera** [comment]
So I was having this same problem a while back, this appears to be an issue with the logic that was pushed back in #307. For whatever reason the ratgdo appears to be defaulting to sending the close command after (in my case) the first open close cycle. I looked back at attempts to implement dry contact toggle in the past and found #284, and forked and re-implemented his version of the dry contact logic. I have been running on this slightly modified version of the dry contact toggle logic since I forked it and I have not had any issues. I am new to github and this specifically is the first project I have had any reason to contribute to so I am not familiar with the correct way of submitting this for a proper fix. I have also adjusted some of the delays for my own personal use case. If you would like me to submit this as a pr please let me know. Thanks!

https://github.com/evil-chimera/esphome-ratgdo/commit/fa9852bd1a1d94a6ee5626bfad8ee350338e1ae4

**Comment by PaulWieland** [comment]
What makes you think it's sending a close command and not a toggle command?

**Comment by PaulWieland** [comment]
Ok, I will try and replicate your test with some some additional logging to see what value is being transmitted.

**Comment by PaulWieland** [comment]
The fundamental issue here is that close and toggle are being triggered simultaneously on the leading edge. That's causing two commands to be sent (Close and Toggle), one of which is ignored. 

To fix this, a delay has to be added before evaluating the GPIO's states.

**Comment by PaulWieland** [comment]
[Fix is here](https://github.com/ratgdo/esphome-ratgdo/tree/dry_contact_toggle_fix). Requires a little more testing before being merged.

**Comment by PaulWieland** [comment]
No, the OTA requires you to upload a compiled firmware file. Unfortunately the github build process which compiles the firmware is [currently broken](https://github.com/ratgdo/esphome-ratgdo/actions/runs/11077344098) and needs to be fixed. 

The only way to run this branch right now is rather convoluted as you would have to clone the repo and build locally. To make matters worse, the yaml files refer to the main branch of the repo, so you have to also know how to deal with that. 

As soon as I'm able to figure out how to fix the github build process, I'll merge the change.

**Comment by PaulWieland** [comment]
The automated build process seems to be fixed and the [PR](https://github.com/ratgdo/esphome-ratgdo/tree/dry_contact_toggle_fix) was merged into the main branch.

**Comment by turbo2ltr** [comment]
It would be useful if this was added to the wiring diagram. Not knowing this was a feature, I set up an automation in HA but was unhappy with the delay. I couldn't believe that there wasn't method to add a simple button closure without having HA in the middle.  But apparently there is! Going to rewire now.
I actually thought the "Wall mounted button" in the wiring diagram was for the simple dry contact button until I saw a picture and realized it was for the "smart" button which I don't have...which is 1/2 the reason I bought the board.  (HA integration was the other half)

**Comment by turbo2ltr** [comment]
Ok the hardware solution is no better than the HA solution, if not a little worse.  Why do I have to hold the button down so long? Surely you can debounce in less than a second.

**Comment by DrkCorners** [comment]
I flashed the current Sec1+ firmware OTA and now this is not working again. I flashed becasue a few times a month the contacts would register a phantom "open" signal. the Open and close contacts are now stuck on "ON" in the web interface.

Something change?

PS: this is on an old 8500, not the 8500W so it should be sec1+

**Comment by DrkCorners** [comment]
All the sudden I now have 2 Ratgdo's that were purchased at the same time with dry contacts stuck.  it appears on one of them its just the "dry contact close" that is stuck on, the other is both open and close stuck on (after firmware update).  On this one I haven't updated the firmware. it has had no changes.

EDT: as a test I unplugged the harness going to the dry contacts on one of the ratgdo.  it still says both dry contacts are "on"
