### ISSUE TITLE
Garage Door Compatibility

### ISSUE THREAD

**Issue by dolfelt** [ratgdo/esphome-ratgdo#320]
Does anyone know if this is compatible with the newer Chamberlain RJO101 jack shaft / wall mount opener or the Lift Master LM98022?

I am moving and looking to upgrade from my RJO20 openers that have been flakey at best (because of the weird Sec+ 1/2)

Does anyone have experience with these openers and know if they are true Sec+ 2.0. I’m assuming that would improve the reliability. 

Thanks!

**Comment by Ikcelaks** [comment]
The compatibility matrix the RJO70 works with ratgdo, and the RJO101 is an update to that model, so it seems really likely that it works. However, I don't own one, so I can't verify it.

https://github.com/PaulWieland/ratgdo/wiki

I can verify that ratgdo works great with the B6713T, which is current generation Chamberlain traditional GDO. It's really nice having all the sensors working, and the cover position is reported spot-on (if I stop the door 60% up, ratdgo reports its position precisely). The ratgdo definitely has a better experience with proper Sec+ 2.0 openers.
