### ISSUE TITLE
Spurious Door Open Messages

### ISSUE THREAD

**Issue by johannesparty** [ratgdo/esphome-ratgdo#322]
ratgdov2.5i, secplus1, LiftMaster 3800.

### Basic

Randomly start getting door opened events; comes in a cluster usually at night.  After a bit, get door closed again.  Might not get any for 24 hours, then get 10-20 times in a few hours.

### Details - other info which might be relevant

- Have myQ hub connected to each garage door also (maybe don't need it anymore; dropped their HomeKit bridge to switch to ratgdo, but left the myQ hub for now as backup/easy warning if left open.
- I have 3 garage doors (1,2,3) with two hubs (hub1: garage 1,2), (hub2: garage 3).
- Garage 2 has backup battery
- All three Garage have 398LM Smart Control Panel and I've turned off motion sensor on all 3
- I do not have any lift master related lights installed
- I do not believe I am losing WiFi connection to any ratgdo (looking at wifi access point data).
- I get "Discard incomplete packet: [38 ...]" on every garage every 10 seconds or so.
- Using HomeBridge to link to HomeKit (separate Linux server).

### Interesting

This problem only occurs with garage door 2.

### Speculation

- loose connection?  doesn't seem that likely.
- related to having two devices connected to single myQ hub?  maybe?
- bad ratgdo module?  maybe? 

### I have attached a few screenshots of the web interface.

Start of open:

<img width="1147" alt="Screenshot 2024-08-24 at 10 31 38 AM" src="https://github.com/user-attachments/assets/b2379ea5-acbf-4e4f-b56d-8feb6292e612">

During open:

<img width="1144" alt="Screenshot 2024-08-24 at 10 33 43 AM" src="https://github.com/user-attachments/assets/2dc02768-a05f-4f91-a4a3-46e62bb2a912">

A bit later:

<img width="1136" alt="Screenshot 2024-08-24 at 10 35 00 AM" src="https://github.com/user-attachments/assets/ce27e470-7dd1-4e84-b86d-8b77927ffc8f">

I am happy to do some debugging if you let me know what to do.  Not really familiar with esphome environment but I guess I can learn!

**Comment by PaulWieland** [comment]
swap the wall panel between two of the doors. I bet the problem follows the panel. 

This is a known issue that gets reposted quite often. The speculated cause is failing capacitors on the wall panel.

**Comment by johannesparty** [comment]
Looks like you are correct. 

I swapped garage 2 and garage 3 wall panels and now the spurious opens happen on garage 3.  I couldn't find any info about bad capacitors on the LM398 and it isn't obvious which capacitors (none seem similar to the often-reported problem capacitors in LM888.  If anybody knows, that would be great.

I did find an LM398 on eBay and will try that.  Otherwise I guess I'll have to switch to LM889LMMC (times three because ... OCD?).

In any case, thanks so much for your help.

**Comment by drxenonbloom** [comment]
I would like to add that I had this same issue on my 398LM. I replaced the two largest capacitors at the bottom of the wall panel (they were 25v 220uf) and it seems to have rectified the issue. I'm still getting the "Discard incomplete packet: [38 ...]" warning when the door is closed but no more random open/close events. Just in case anyone else has this issue.

**Comment by vicfalc09** [comment]
> I would like to add that I had this same issue on my 398LM. I replaced the two largest capacitors at the bottom of the wall panel (they were 25v 220uf) and it seems to have rectified the issue. I'm still getting the "Discard incomplete packet: [38 ...]" warning when the door is closed but no more random open/close events. Just in case anyone else has this issue.

I did the same (replaced the capacitors) it was working well for a couple days and then last night it started getting random closed notifications in HomeKit.  Are you guys running the ESP firmware or the Ratgdo HomeKit firmware?
