### ISSUE TITLE
Is it possible to replace the ESP-12F on the ratgdo v2.53i kit with ESP32 with same pinout?

### ISSUE THREAD

**Issue by t0ny-peng** [ratgdo/esphome-ratgdo#328]
My garage has several bluetooth devices that can be tracked by ESP32, yet the ratgdo v2.53i kit came with ESP-12F soldered. Is it possible to desolder the ESP-12F out and replace it with a compatible-pinout ESP32? Like `ESP32-C3F`. Just curious if anyone has done it. Like, does it work all the peripherals, resistors, MOSFETs, etc. Can it be flashed directly using the micro USB port?

Thanks!

**Comment by PaulWieland** [comment]
No it is not possible.
