### ISSUE TITLE
After router reboot ratgdo reports door 'was closed' and light 'turned off'

### ISSUE THREAD

**Issue by httr-1991** [ratgdo/esphome-ratgdo#341]
Every evening I reboot I have a scheduled reboot of my router. When the ratgdo connects after this reboot I'm getting status updates in Home Assistant that the door 'was closed' and the light was 'turned off' when obviously there was no action taken. Since I have automations and alerts based on these statuses, its creating a small headache.

Hardware: ratgdo 2.53i with ESPhome

![image](https://github.com/user-attachments/assets/a8a1b468-0c72-4563-9fad-ac40a2392ada)

Let me know if more information is needed, happy to help and thank you!

**Comment by doctorkb** [comment]
As a workaround, if you use Node-RED for your automations, the HA module has an option to ignore status changes when the previous status is "unavailable"...
![image](https://github.com/user-attachments/assets/103e20ce-fe5f-435c-80b2-afb17083b5e0)
