### ISSUE TITLE
Request: mqtt support

### ISSUE THREAD

**Issue by jonathanjacob** [ratgdo/esphome-ratgdo#35]
Any chance for direct MQTT support similar to the original ratgdo?

I tried via the yaml file but had an issue.

**Comment by jonathanjacob** [comment]
also thanks for all of the hard work!

**Comment by jonathanjacob** [comment]
@mariusmuja any thoughts?

**Comment by mariusmuja** [comment]
Esphome requires the use of the yaml file to configure mqtt. You need to to replace:
```
api:
  id: api_server
```
in file https://github.com/ESPHome-RATGDO/esphome-ratgdo/blob/main/static/v2board_esp8266_d1_mini_lite.yaml
with something like:
```
mqtt:
  broker: ...
  username: ...
  password: ...
```
Then upload the firmware to the device by running: `esphome run v2board_esp8266_d1_mini_lite.yaml`

**Comment by PaulWieland** [comment]
This isn't really possible to do because of the way ESPHome works. We've been discussing this and there doesn't seem to be a viable way to have one firmware built on ESPHome that also supports MQTT.  You have to custom compile your own ESPHome firmware which has your MQTT credentials baked in.
