### ISSUE TITLE
What is the motion sensor for?

### ISSUE THREAD

**Issue by J-Pipe** [ratgdo/esphome-ratgdo#67]
Don't see any documentation for the motion sensor. The ratgdo project doesn't look like it has a motion sensor. Not sure where this came from. Not seeing the value ever change.

**Comment by YBonline** [comment]
> Don't see any documentation for the motion sensor. The ratgdo project doesn't look like it has a motion sensor. Not sure where this came from. Not seeing the value ever change.

This is the status of the motion sensor that is located on some of the wall buttons. If your wall button doesn't have a motion sensor, it will not ever change.

**Comment by mkaatman** [comment]
Is the motion sensor only in the esphome version or does mqtt 2.1 have it as well?

**Comment by restauffer** [comment]
I an using MQTT with a SEC +1 gdo and I do not see the motion detector exposed as a topic in MQTT. It seems the ESP version has more features but  I can't use it with a SEC +1 GDO.

**Comment by PaulWieland** [comment]
Motion detection isn’t possible with sec + 1.0.
