### ISSUE TITLE
Question:  45ACT power supply connection

### ISSUE THREAD

**Issue by jgosnell56** [ratgdo/esphome-ratgdo#90]
I am seeing an issue and wondered if anyone saw this or what could be causing my issue.  When I use an external power source for my Ratgdo, everything works properly.  When I pull the 3.3v source from the board following the diagram here (very bottom) [https://paulwieland.github.io/ratgdo/03_wiring_soldered.html](url), my remotes drastically lose distance.  They are pretty much useless unless I am standing inside the garage when pressing a button.  I assume I am drawing too much power from the board causing the remote receiver to be underpowered.  Is there another 3.3v source on the board I could solder to and try?

**Comment by mariusmuja** [comment]
I'm using 3.3V from inside the GDO, but I haven't tested the range on the remote (I stopped using the remote altogether and switched to using HA on the cellphone instead). Maybe there's not enough power on that rail in case of your GDO, in which case maybe you could try using a buck converter connected to the 12V rail.
